export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const QUIZ_ADD_LOADING = "QUIZ_ADD_LOADING";
export const QUIZ_ADD_SUCCESS = "QUIZ_ADD_SUCCESS";
export const QUIZ_ADD_FAILED = "QUIZ_ADD_FAILED";
export const SELECT_OPTION = "SELECT_OPTION";
